package com.reelsplit.sharing

import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.net.Uri
import android.os.Build
import androidx.core.content.FileProvider
import com.reelsplit.domain.sharing.WhatsAppSharerContract
import dagger.hilt.android.qualifiers.ApplicationContext
import timber.log.Timber
import java.io.File
import javax.inject.Inject

// =============================================================================
// WhatsAppSharer
// =============================================================================

/**
 * Production implementation of [WhatsAppSharerContract].
 *
 * Handles all WhatsApp integration using Android Intents:
 * - **Status sharing** via Meta's official `SEND_MEDIA_TO_STATUS` action
 * - **Chat sharing** via the standard `ACTION_SEND` with WhatsApp package filter
 * - **Installation detection** via [PackageManager]
 *
 * ## FileProvider
 * Video files are shared as content URIs generated by [FileProvider] with
 * authority `{applicationId}.fileprovider`. The paths served must match
 * those declared in `res/xml/file_paths.xml`.
 *
 * ## Threading
 * All methods are safe to call from any thread. Intent launching uses
 * [Intent.FLAG_ACTIVITY_NEW_TASK] since we launch from application context,
 * which starts a new task stack rather than requiring an existing Activity.
 *
 * ## Security
 * - Uses [FileProvider] instead of `file://` URIs for Android 7.0+ compatibility
 * - Grants temporary read permission via [Intent.FLAG_GRANT_READ_URI_PERMISSION]
 * - Only grants access to the specific file being shared
 *
 * @property context Application context for PackageManager access, FileProvider
 *   URI generation, and starting Activities.
 */
class WhatsAppSharer @Inject constructor(
    @ApplicationContext private val context: Context
) : WhatsAppSharerContract {

    // =========================================================================
    // Installation Check
    // =========================================================================

    /**
     * Checks if WhatsApp is installed on the device.
     *
     * Uses [PackageManager.getPackageInfo] for reliable detection across all
     * API levels. On API 30+ (R), the app must declare a `<queries>` element
     * in the manifest for WhatsApp's package, or the query will return false
     * even if WhatsApp is installed. Our manifest includes the necessary
     * `<queries>` declaration to satisfy this requirement.
     *
     * Note: The API-level branching below (TIRAMISU / API 33) is for the
     * [PackageManager.getPackageInfo] overload that accepts
     * [PackageManager.PackageInfoFlags], not for the `<queries>` requirement.
     *
     * @return `true` if WhatsApp (`com.whatsapp`) is installed, `false` otherwise
     */
    override fun isWhatsAppInstalled(): Boolean {
        return try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
                context.packageManager.getPackageInfo(
                    WHATSAPP_PACKAGE,
                    PackageManager.PackageInfoFlags.of(0)
                )
            } else {
                @Suppress("DEPRECATION")
                context.packageManager.getPackageInfo(WHATSAPP_PACKAGE, 0)
            }
            true
        } catch (e: PackageManager.NameNotFoundException) {
            Timber.d("WhatsApp is not installed")
            false
        }
    }

    // =========================================================================
    // Share to Status
    // =========================================================================

    /**
     * Shares a video file to WhatsApp Status.
     *
     * Uses Meta's official WhatsApp Status API action
     * (`com.whatsapp.intent.action.SEND_MEDIA_TO_STATUS`) to open the
     * WhatsApp Status composer directly with the video pre-attached.
     *
     * @param videoPath The absolute path to the video file to share
     * @throws IllegalArgumentException if the file does not exist or is not
     *   accessible via [FileProvider]
     * @throws android.content.ActivityNotFoundException if WhatsApp is not installed
     */
    override fun shareToWhatsAppStatus(videoPath: String) {
        val videoUri = getFileProviderUri(videoPath)
        Timber.d("Sharing to WhatsApp Status: %s", videoPath)

        val intent = createShareIntent(
            action = ACTION_SEND_TO_STATUS,
            videoUri = videoUri
        )
        context.startActivity(intent)
    }

    // =========================================================================
    // Share to Chat
    // =========================================================================

    /**
     * Shares a video file to WhatsApp chat.
     *
     * Opens WhatsApp's standard share flow via [Intent.ACTION_SEND],
     * allowing the user to select a contact or group to send the video to.
     *
     * @param videoPath The absolute path to the video file to share
     * @throws IllegalArgumentException if the file does not exist or is not
     *   accessible via [FileProvider]
     * @throws android.content.ActivityNotFoundException if WhatsApp is not installed
     */
    override fun shareToWhatsAppChat(videoPath: String) {
        val videoUri = getFileProviderUri(videoPath)
        Timber.d("Sharing to WhatsApp Chat: %s", videoPath)

        val intent = createShareIntent(
            action = Intent.ACTION_SEND,
            videoUri = videoUri
        )
        context.startActivity(intent)
    }

    // =========================================================================
    // Private Helpers
    // =========================================================================

    /**
     * Creates a share [Intent] configured for WhatsApp with the given action
     * and video URI.
     *
     * Common configuration applied to both Status and Chat intents:
     * - Targets WhatsApp's package to bypass the system share sheet
     * - Sets MIME type to `video/mp4`
     * - Attaches the video as [Intent.EXTRA_STREAM]
     * - Grants temporary read permission for the content URI
     * - Uses [Intent.FLAG_ACTIVITY_NEW_TASK] for application-context launching
     *
     * @param action The intent action (e.g., [ACTION_SEND_TO_STATUS] or
     *   [Intent.ACTION_SEND])
     * @param videoUri The [FileProvider] content URI of the video to share
     * @return A fully configured [Intent] ready to be passed to
     *   [Context.startActivity]
     */
    private fun createShareIntent(action: String, videoUri: Uri): Intent {
        return Intent(action).apply {
            setPackage(WHATSAPP_PACKAGE)
            type = MIME_TYPE_VIDEO
            putExtra(Intent.EXTRA_STREAM, videoUri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
    }

    /**
     * Generates a content URI for the given file path via [FileProvider].
     *
     * The file must reside within one of the paths declared in
     * `res/xml/file_paths.xml`:
     * - `cache-path/` — downloaded videos and split segments (context.cacheDir)
     * - `external-files-path/videos/` — saved/exported videos (context.getExternalFilesDir)
     * - `files-path/split/` — processing artifacts (context.filesDir)
     *
     * @param filePath The absolute path to the file
     * @return A content URI (`content://com.reelsplit.fileprovider/...`)
     * @throws IllegalArgumentException if the file doesn't exist or isn't
     *   within a configured FileProvider path
     */
    private fun getFileProviderUri(filePath: String): Uri {
        val file = File(filePath)
        require(file.exists()) {
            "Video file does not exist: $filePath"
        }
        return FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            file
        )
    }

    internal companion object {
        /** WhatsApp package name for intent targeting and manifest queries. */
        internal const val WHATSAPP_PACKAGE = "com.whatsapp"

        /** Official WhatsApp Status sharing action. */
        private const val ACTION_SEND_TO_STATUS =
            "com.whatsapp.intent.action.SEND_MEDIA_TO_STATUS"

        /** MIME type for video files. */
        private const val MIME_TYPE_VIDEO = "video/mp4"
    }
}
